### ISSUE TITLE
Error: Redis connection to redis:6379 failed - getaddrinfo ENOTFOUND redis

### ISSUE THREAD

**Issue by malmax** [dokku/dokku-redis#110]
Dokku version 0.11.3 and 0.12.12
Created app and two services: redis and postgres.
Linked both to app. With postgres is all ok.

I try to connect to Redis like this
```javascript
import Redis from 'ioredis';

const redis =
  process.env.NODE_ENV === 'production'
    ? new Redis(process.env.REDIS_URL)
    : new Redis();
export default redis;
```
but get an error
```
Error: Redis connection to redis:6379 failed - getaddrinfo ENOTFOUND redis redis:6379
           at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)
       Emitted 'error' event at:
           at RedisStore.<anonymous> (/gamebuy/node_modules/koa-session-redis-store/lib/redis_store.js:35:10)
           at RedisClient.emit (events.js:180:13)
           at RedisClient.emit (domain.js:422:20)
           at RedisClient._29d‍.r.RedisClient.on_error (/gamebuy/node_modules/redis/index.js:406:14)
           at Socket.<anonymous> (/gamebuy/node_modules/redis/index.js:279:14)
           at Socket.emit (events.js:180:13)
           at Socket.emit (domain.js:422:20)
           at emitErrorNT (internal/streams/destroy.js:64:8)
           at process._tickCallback (internal/process/next_tick.js:178:19)
       error Command failed with exit code 1.
```

**Comment by pak11273** [comment]
I'm assuming you are following Ben Awad's airbnb tutorial.  Did you come up with a solution or is this still an issue?

**Comment by OmarAbdo** [comment]
having the same issue over here

**Comment by josegonzalez** [comment]
@OmarAbdo what is the exact error you are seeing?

The original user had this error because they weren't actually using the `REDIS_URL` - likely because `NODE_ENV` was somehow not set to production.

**Comment by OmarAbdo** [comment]
the error was failed to connect to port 6379 on my windows machine. Anyway I solved the issue by using a Redis docker image and it worked perfectly after then
