### ISSUE TITLE
SocketError: getaddrinfo: Name or service not known

### ISSUE THREAD

**Issue by glennpjones** [dokku/dokku-redis#69]
Hi,

First of all, thanks for dokku-redis, it's awesome. I hope I'm in the right place to ask this question.

The rails app in question has a staging environment (on port 2851, no dedicated subdomain) with a dokku-redis service linked to it (for sidekiq). Some sidekiq jobs work, some don't. Debugging that, when I manually try to connect to the redis service, I get this:

```
irb(main):004:0> output = Redis.new(:url => ENV["REDIS_URL"]).info
SocketError: getaddrinfo: Name or service not known
	from /app/vendor/bundle/ruby/2.3.0/gems/redis-3.3.1/lib/redis/connection/ruby.rb:212:in `getaddrinfo'
	from /app/vendor/bundle/ruby/2.3.0/gems/redis-3.3.1/lib/redis/connection/ruby.rb:212:in `connect'
	from /app/vendor/bundle/ruby/2.3.0/gems/redis-3.3.1/lib/redis/connection/ruby.rb:295:in `connect'
	from /app/vendor/bundle/ruby/2.3.0/gems/redis-3.3.1/lib/redis/client.rb:336:in `establish_connection'
	from /app/vendor/bundle/ruby/2.3.0/gems/redis-3.3.1/lib/redis/client.rb:101:in `block in connect'
	from /app/vendor/bundle/ruby/2.3.0/gems/redis-3.3.1/lib/redis/client.rb:293:in `with_reconnect'
	from /app/vendor/bundle/ruby/2.3.0/gems/redis-3.3.1/lib/redis/client.rb:100:in `connect'
	from /app/vendor/bundle/ruby/2.3.0/gems/redis-3.3.1/lib/redis/client.rb:364:in `ensure_connected'
	from /app/vendor/bundle/ruby/2.3.0/gems/redis-3.3.1/lib/redis/client.rb:221:in `block in process'
	from /app/vendor/bundle/ruby/2.3.0/gems/redis-3.3.1/lib/redis/client.rb:306:in `logging'
	from /app/vendor/bundle/ruby/2.3.0/gems/redis-3.3.1/lib/redis/client.rb:220:in `process'
	from /app/vendor/bundle/ruby/2.3.0/gems/redis-3.3.1/lib/redis/client.rb:120:in `call'
	from /app/vendor/bundle/ruby/2.3.0/gems/redis-3.3.1/lib/redis.rb:251:in `block in info'
	from /app/vendor/bundle/ruby/2.3.0/gems/redis-3.3.1/lib/redis.rb:58:in `block in synchronize'
	from /app/vendor/ruby-2.3.1/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
	from /app/vendor/bundle/ruby/2.3.0/gems/redis-3.3.1/lib/redis.rb:58:in `synchronize'
	from /app/vendor/bundle/ruby/2.3.0/gems/redis-3.3.1/lib/redis.rb:250:in `info'
	from (irb):4
	from /app/vendor/bundle/ruby/2.3.0/gems/railties-4.2.6/lib/rails/commands/console.rb:110:in `start'
	from /app/vendor/bundle/ruby/2.3.0/gems/railties-4.2.6/lib/rails/commands/console.rb:9:in `start'
	from /app/vendor/bundle/ruby/2.3.0/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /app/vendor/bundle/ruby/2.3.0/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /app/vendor/bundle/ruby/2.3.0/gems/railties-4.2.6/lib/rails/commands.rb:17:in `<top (required)>'
	from /app/bin/rails:4:in `require'
	from /app/bin/rails:4:in `<main>'
```

` REDIS_URL = "redis://staging_jobstore:alongsecret@dokku-redis-staging-jobstore:6379"`

Any ideas on what is causing this? If I haven't said it before, I'm not sure this issue is related to dokku-redis but from my side, it seems so. I've tried to re-promote the service to the app, to no avail.

**Comment by josegonzalez** [comment]
Is that irb from a container run, or from your local irb?

**Comment by glennpjones** [comment]
container run, `rails c`

**Comment by josegonzalez** [comment]
That sounds like the container isn't linked to the service. Can you do the following:

```
dokku docker-options APP
```

And paste the output?

**Comment by glennpjones** [comment]
```
Build options:
    --link dokku.postgres.staging_db:dokku-postgres-staging-db
    --link dokku.redis.staging_jobstore:dokku-redis-staging-jobstore
Deploy options:
    --link dokku.postgres.staging_db:dokku-postgres-staging-db
    --link dokku.redis.staging_jobstore:dokku-redis-staging-jobstore
    -v /var/lib/dokku/data/storage/staging/public/uploads:/app/public/uploads
Run options:
    --link dokku.postgres.staging_db:dokku-postgres-staging-db
    -v /var/lib/dokku/data/storage/staging/public/uploads:/app/public/uploads
```

So, it seems ` --link dokku.redis.staging_jobstore:dokku-redis-staging-jobstore` is missing from Run options?

**Comment by glennpjones** [comment]
```
$ dokku redis:link staging_jobstore staging
Already linked as REDIS_URL
```

**Comment by josegonzalez** [comment]
Right, not clear how that happened - probably an accident on your end :( - but you can just add it using the `docker-options` plugin.

**Comment by glennpjones** [comment]
Yes, likely ! Thank you for helping me figure out what happened anyway 👍  :)
